language: node_js
node_js:
  - "12"
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
  - frontend/node_modules
install:
  - cd frontend && npm ci
  - npm ci
script:
  - npm run lint
  - npm run
  - npm run coveralls
